name: Build

on: 
  push: 
    branches: 
      - develop
  pull_request: 
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Los clones superficiales deben estar deshabilitados para mejor relevancia del análisis

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'  # O puedes usar 'zulu', 'adopt', etc. según prefieras

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub proporciona automáticamente este token
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}    # Debe estar configurado en los secrets
